### ISSUE TITLE
Cannot bind composite resource: cannot bind claim that references a different composite resource

### ISSUE THREAD

**Issue by eya-rabeh** [vfarcic/crossplane-sql#1]
I've set up a Kubernetes cluster and integrated Crossplane into it. Using Crossplane, I've successfully orchestrated an AWS EKS cluster utilizing the dot-k8s package. This EKS cluster has been appropriately configured with the config-sql. My current goal is to deploy AWS RDS on top of this EKS cluster using the config-sql. However, I'm encountering a challenge after creating a SQLClaim. There's a short delay, and subsequently, I'm confronted with an error message that reads "cannot bind composite resources," which is visible in the attached image. Despite my efforts to troubleshoot, I haven't been able to identify a solution. Could you please extend your support in addressing this issue?
<img width="1701" alt="Screenshot 2023-08-21 at 16 08 56" src="https://github.com/vfarcic/crossplane-sql/assets/48928985/9795b626-3a56-4df9-a66a-d36ba13ce349">

**Comment by vfarcic** [comment]
Can you create a Gist with the commands you executed so that I reproduce it in my cluster?

**Comment by eya-rabeh** [comment]
Absolutely, I've successfully crafted my own crossplane-k8s package following to your configuration. The EKS composition includes both config-gitops and config-sql components. You can find the details in this [gist file](https://gist.github.com/eya-rabeh/7a5f39917358a5698dc3265a433692d5).

**Comment by vfarcic** [comment]
Hmmm... I could not find the issue (it could be because I'm tired; it's 2am where I am). How about a live troubleshooting session? If that works for you, please pick any time that works for you from https://calendar.app.google/5XsvFJriLzF1s3xeA.

**Comment by eya-rabeh** [comment]
I would love to, thank you so much 🥇

**Comment by eya-rabeh** [comment]
Adding the `application.resourceTrackingMethod: annotation` in the argoCD values, made it work. Thank you.

**Comment by vfarcic** [comment]
Can you make a PR?
